"""custom errors in this package"""

from prescyent.utils.errors.custom_exception import CustomException
from prescyent.utils.errors.empty_dataset_exception import EmptyDatasetException
