"""custom errors in this package"""

from prescyent.utils.errors.dataset.empty_dataset_exception import DatasetEmptyException
